steepestAscent8Puzzle;
figure('Name','Steepest Ascent - 8Puzzle');
plot(a);
title('Steepest Ascent - 8Puzzle');
xlabel('Try');
ylabel('Cost');
simulateAnnealing8Puzzle;
figure('Name','Simulated Annealing - 8Puzzle');
plot(c);
title('Simulated Annealing - 8Puzzle');
xlabel('Try');
ylabel('Cost');
firstChoice8Puzzle;
figure('Name','First Choice - 8Puzzle');
plot(b);
title('First Choice - 8Puzzle');
xlabel('Try');
ylabel('Cost');
steepestAscent8Queens;
figure('Name','Steepest Ascent - 8Queens');
plot(d);
title('Steepest Ascent - 8Queens');
xlabel('Try');
ylabel('Cost');
simulateAnnealing8Queens;
figure('Name','Simulated Annealing - 8Queens');
plot(e);
title('Simulated Annealing - 8Queens');
xlabel('Try');
ylabel('Cost');
firstChoice8Queens;
figure('Name','First Choice - 8Queens');
plot(f);
title('First Choice - 8Queens');
xlabel('Try');
ylabel('Cost');

